---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          imagePullPolicy: IfNotPresent
          image: ghost:3.41.3-alpine
          ports:
            - containerPort: 2368
              name: ghost
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: ghost-pvc
      volumes:
        - name: ghost-pvc
          persistentVolumeClaim:
            claimName: ghost-pvc
